### ISSUE TITLE
Add support to clean up KMS customer managed keys

### ISSUE THREAD

**Issue by atqhg23** [mlevit/aws-auto-cleanup#133]
**Is your feature request related to a problem? Please describe.**
While the cost of KMS keys isn't as high at $1/month, keys can quickly build up, specially in dev environments, driving up cost.

**Describe the solution you'd like**
Add support to clean up KMS keys.

**Describe alternatives you've considered**
There are some options to help reduce KMS cost like using S3 bucket keys, but it seems like cleaning up KMS keys is a good approach as well.

**Comment by mlevit** [comment]
@atqhg23 mind testing? https://github.com/mlevit/aws-auto-cleanup/tree/kms-cleanup

**Comment by atqhg23** [comment]
Thank you! Sorry for the late response, will test today and get back with the results

**Comment by atqhg23** [comment]
Apologies for the delay. Everything worked as expected when I was testing.

- allowlist tests successful - KMS keys that were allowlisted were not deleted (tested in us-east-1 and us-east-2)
- delete tests successful - KMS keys marked as **DELETE** were updated to a **pending deletion** status (tested in us-east-1 and us-east-2)

I did have one question about the **SKIP - STATE** action. I looked over the code, but just wanted to confirm, this action only shows up for keys that do not have the status set to **enabled** right?

**Comment by mlevit** [comment]
You're all good @atqhg23. Just tweaked the code a little to skip keys owned by `AWS` completely instead of adding them to the processed list with a state of `SKIP - STATE`.

Keys in a state other than `Enabled` will have the action of `SKIP - STATE`. I've also added a INFO log message for those keys too.

**Comment by atqhg23** [comment]
Thanks for confirming. Made those updates and verified that AWS managed keys are not showing up. 

I also submitted a pull request to update the app readme - https://github.com/mlevit/aws-auto-cleanup/pull/134. Feel free to make any changes.

Thanks again for working on this, greatly appreciated!
